### ISSUE TITLE
Unable to build production site in Amplify Gen2

### ISSUE THREAD

**Issue by emachnic** [aws-amplify/amplify-backend#1034]
### Environment information

```plain text
System:
  OS: macOS 14.3
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 31.59 MB / 16.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 20.5.1 - /usr/local/bin/node
  Yarn: 1.22.18 - ~/.yarn/bin/yarn
  npm: 9.8.0 - /usr/local/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 0.11.0
  @aws-amplify/backend-cli: 0.11.0
  aws-amplify: 6.0.15
  aws-cdk: 2.126.0
  aws-cdk-lib: 2.126.0
  typescript: 5.3.3
AWS environment variables:
  AWS_PROFILE = oaccoe-sandbox-owner
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

I have a Next.js 14 application using the App Router that I'm trying to deploy to Amplify Gen2. I'm able to create a production build locally but when I push the code, I'm unable to get a successful build in Amplify. The relevant output follows:

```shell
2024-02-15T13:46:56.599Z [INFO]: ▲ Next.js 14.1.0
2024-02-15T13:46:56.599Z [INFO]: 
2024-02-15T13:46:56.676Z [INFO]: Creating an optimized production build ...
2024-02-15T13:47:20.690Z [WARNING]: (node:1452) [DEP_WEBPACK_MODULE_UPDATE_HASH] DeprecationWarning: Module.updateHash: Use new ChunkGraph API
                                    (Use `node --trace-deprecation ...` to show where the warning was created)
2024-02-15T13:47:24.412Z [INFO]: ✓ Compiled successfully
2024-02-15T13:47:24.419Z [INFO]: Linting and checking validity of types ...
2024-02-15T13:47:33.537Z [INFO]: Collecting page data ...
2024-02-15T13:47:35.681Z [INFO]: Generating static pages (0/8) ...
2024-02-15T13:47:36.001Z [INFO]: Generating static pages (2/8)
2024-02-15T13:47:36.061Z [INFO]: Generating static pages (4/8)
2024-02-15T13:47:36.172Z [INFO]: Generating static pages (6/8)
2024-02-15T13:47:36.279Z [WARNING]: TypeError: Cannot read properties of undefined (reading 'clientModules')
                                    at /codebuild/output/src1630635012/src/ccoe-amplify_gen2_example/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:199008
                                    at rW (/codebuild/output/src1630635012/src/ccoe-amplify_gen2_example/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:14861)
                                    at nM (/codebuild/output/src1630635012/src/ccoe-amplify_gen2_example/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47419)
                                    at nN (/codebuild/output/src1630635012/src/ccoe-amplify_gen2_example/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64674)
                                    at nM (/codebuild/output/src1630635012/src/ccoe-amplify_gen2_example/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61233)
                                    at nN (/codebuild/output/src1630635012/src/ccoe-amplify_gen2_example/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64674)
                                    at nI (/codebuild/output/src1630635012/src/ccoe-amplify_gen2_example/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:46806)
                                    at nM (/codebuild/output/src1630635012/src/ccoe-amplify_gen2_example/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47570)
                                    at nN (/codebuild/output/src1630635012/src/ccoe-amplify_gen2_example/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64674)
                                    at nM (/codebuild/output/src1630635012/src/ccoe-amplify_gen2_example/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61233)
                                    TypeError: Cannot read properties of undefined (reading 'clientModules')
                                    at /codebuild/output/src1630635012/src/ccoe-amplify_gen2_example/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:199008
                                    at rW (/codebuild/output/src1630635012/src/ccoe-amplify_gen2_example/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:14861)
                                    at nM (/codebuild/output/src1630635012/src/ccoe-amplify_gen2_example/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47419)
                                    at nN (/codebuild/output/src1630635012/src/ccoe-amplify_gen2_example/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64674)
                                    at nG (/codebuild/output/src1630635012/src/ccoe-amplify_gen2_example/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:72265)
                                    at AsyncLocalStorage.run (node:async_hooks:338:14)
                                    at Timeout._onTimeout (/codebuild/output/src1630635012/src/ccoe-amplify_gen2_example/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:88128)
                                    at listOnTimeout (node:internal/timers:569:17)
                                    at process.processTimers (node:internal/timers:512:7)
                                    Error occurred prerendering page "/medications". Read more: https://nextjs.org/docs/messages/prerender-error
                                    TypeError: Cannot read properties of undefined (reading 'clientModules')
                                    at /codebuild/output/src1630635012/src/ccoe-amplify_gen2_example/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:199008
                                    at rW (/codebuild/output/src1630635012/src/ccoe-amplify_gen2_example/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:14861)
                                    at nM (/codebuild/output/src1630635012/src/ccoe-amplify_gen2_example/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47419)
                                    at nN (/codebuild/output/src1630635012/src/ccoe-amplify_gen2_example/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64674)
                                    at nG (/codebuild/output/src1630635012/src/ccoe-amplify_gen2_example/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:72265)
                                    at AsyncLocalStorage.run (node:async_hooks:338:14)
                                    at Timeout._onTimeout (/codebuild/output/src1630635012/src/ccoe-amplify_gen2_example/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:88128)
                                    at listOnTimeout (node:internal/timers:569:17)
                                    at process.processTimers (node:internal/timers:512:7)
2024-02-15T13:47:36.279Z [INFO]: ✓ Generating static pages (8/8)
2024-02-15T13:47:36.284Z [WARNING]: 
2024-02-15T13:47:36.284Z [WARNING]: > Export encountered errors on following paths:
                                    /medications/(overview)/page: /medications
2024-02-15T13:47:36.310Z [ERROR]: !!! Build failed
2024-02-15T13:47:36.310Z [INFO]: Please read more about Amplify Hosting's support for SSR frameworks to find if your build failure is related to an unsupported feature: https://docs.aws.amazon.com/amplify/latest/userguide/amplify-ssr-framework-support.html. You may also find this troubleshooting guide useful: https://docs.aws.amazon.com/amplify/latest/userguide/troubleshooting-ssr-deployment.html
2024-02-15T13:47:36.310Z [ERROR]: !!! Error: Command failed with exit code 1
2024-02-15T13:47:36.310Z [INFO]: # Starting environment caching...
2024-02-15T13:47:36.310Z [INFO]: # Uploading environment cache artifact...
2024-02-15T13:47:36.433Z [INFO]: # Uploaded environment cache artifact
2024-02-15T13:47:36.433Z [INFO]: # Environment caching completed
Terminating logging...
```

I have a Gist at https://gist.github.com/emachnic/03e6d296ea6e8d8a6f457d67878400b0 with a couple of code files but can add more if more information is needed.

Is this just an issue with me not knowing how React works well enough or is there some other issue I should be looking into?

**Comment by emachnic** [comment]
I've reworked the code a bit and moved the medications fetching to a separate file and awaiting them in the page.tsx file. I'm now getting an error with the Next.js cookies client code that I think sheds a bit of light on my issues, though I'm not completely sure how to fix them as I just followed the directions in the Quickstart. Here's a line from the new log file and the error is being thrown from the actions.ts file

description: "Page couldn't be rendered statically because it used `cookies`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error",
digest: 'DYNAMIC_SERVER_USAGE'
}
Error: Failed to fetch medications.

Here is my `fetchMedications` code 

```
export async function fetchMedications() {
  try {
    const { data: medications, errors } =
      await cookiesClient.models.Medication.list();

    return medications;
  } catch (error) {
    console.error("Database Error:", error);
    throw new Error("Failed to fetch medications.");
  }
}
```

**Comment by Jay2113** [comment]
@emachnic 👋 , thanks for reaching out. I observed that your Next app uses v14.1.0 and since you are able to run a production build of it locally I wonder if the issue persists with this latest Next.js version. This maybe related: https://github.com/vercel/next.js/issues/58576.

Can you try to downgrade your Next version to v14.0.1 and use the Amplify AL2023 build image on the Gen2 app? Steps are outlined here: https://docs.amplify.aws/gen2/start/quickstart/nextjs-pages-router/#connect-branch-in-the-amplify-console

**Comment by Jay2113** [comment]
As discussed in the community discord server, the issue was resolved after removing the try/catch block and the builds are now completing successfully. Closing the issue but feel free to open a new one if you are experiencing issues with Amplify Gen 2. Thanks!

**Comment by saitharunsai** [comment]
> As discussed in the community discord server, the issue was resolved after removing the try/catch block and the builds are now completing successfully. Closing the issue but feel free to open a new one if you are experiencing issues with Amplify Gen 2. Thanks!

@Jay2113 I have downgraded, but the same issue persists. Can you suggest the NodeJS version to be used? my current Node.js version is v20.11.1 and tried even with 18.17.0
