### ISSUE TITLE
Node v20.12.x causes segmentation fault with `npx ampx sandbox` and latest version of node due to parcelWatcher

### ISSUE THREAD

**Issue by deconduino** [aws-amplify/amplify-backend#1297]
### Environment information

```plain text
System:
  OS: Linux 5.15 Arch Linux
  CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
  Memory: 11.50 GB / 15.59 GB
  Shell: /usr/bin/zsh
Binaries:
  Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
  Yarn: undefined - undefined
  npm: 10.5.2 - ~/.nvm/versions/node/v20.12.2/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 0.13.0-beta.16
  @aws-amplify/backend-cli: 0.12.0-beta.18
  aws-amplify: 6.0.28
  aws-cdk: 2.137.0
  aws-cdk-lib: 2.137.0
  typescript: 5.4.5
```

### Description

Ran into this one today, putting it here in case anyone else hits the same issue. Running `npx amplify sandbox` will result in a segmentation fault when using node v20.12 if there are any wildcards in the `.gitignore` file due to an issue with parcelWatcher.

Workaround - rollback to node v20.11 until resolved.

https://github.com/parcel-bundler/watcher/issues/170

**Comment by jgomezupstart13** [comment]
thank you for this!!! really really thank you, I was going crazy trying to find a way to solve it.

**Comment by ykethan** [comment]
@deconduino thank you for reporting this. Marking this as bug to track this.

**Comment by pchinjr** [comment]
thanks for reporting, I was using Node v.20.2 and found the same error, I rolled Node back to v.20.11.0 and sandbox is working again.

**Comment by TheRealBenForce** [comment]
Thank you!

`nvm install --lts` bringing me to v20.13.1 worked for me

**Comment by brunohnq** [comment]
Yep, same here, switching to the node lts version fixed

**Comment by satya1395** [comment]
switching to lts did not work for me.

**Comment by supertick** [comment]
Using a relatively new version of node, and walking through the amplify gen 2 docs step by step including using the aws supplied react vite template gives you Segmentation fault (Abort).  Not the best user experience.
Understandably, its not aws's bug - but until its fixed I would think perhaps AWS should modify their .gitignore of the template (removing wildcards)  to provide a better user experience.

Removing all wildcards from .gitignore worked for me - thanks for the tip.

**Comment by juaose** [comment]
Switched to v20.11  && ITS WORKING FINE

**Comment by josefaidt** [comment]
Linked issue is resolved and templates have been updated. Closing this issue

**Comment by JosChavz** [comment]
Issue occurring on v22.11.0 for me.

Removing all wildcards fixed the issue.

```
.amplify
amplify_outputs*
amplifyconfiguration*
```

Not sure how to feel when I had to omit wildcards for amplify files, though. I gave them JSON extensions... but not sure if that was the best approach.

**Comment by mar33p** [comment]
Tried rolling back to 20.11, 20.13, and 22.11 and I'm still getting a segmentation fault when running `npx ampx sandbox` 
Tried removing all wildcards from the gitignore, no luck there either.

**Comment by Josh-Weston** [comment]
Issue remains with v22.14.0

**Comment by jordauld1** [comment]
Encountering Segmentation fault on v22.15.1

**Comment by syardumi** [comment]
problem still exists in v22.17.0

**Comment by L-Luppi** [comment]
Just checked Amazon Q for this error and got this response 

Based on the latest AWS Amplify documentation, here are the current requirements and installation steps for ampx sandbox:

Latest Supported Node.js Version
✅ Node.js v18.16.0 or later is the minimum requirement

Recommended: Node.js v18.x or v20.x (LTS versions)
Latest tested: Node.js v20.x

used nvm install 20 to get the last 20.x.x version and voilà ... backend initialized
