### ISSUE TITLE
New UI: Cypress integration is missing.

### ISSUE THREAD

**Issue by hackmajoris** [aws-amplify/amplify-backend#1623]
### Environment information

```plain text
Not relevant
```

### Description

In the previous console UI, there was a 'TEST' step where Cypress tests were executed, and it generated comprehensive reports, including screenshots and videos, as detailed in this AWS blog post: https://aws.amazon.com/blogs/mobile/running-end-to-end-cypress-tests-for-your-fullstack-ci-cd-deployment-with-amplify-console/.  

However, with the new UI, the process has changed significantly. While you can still run Cypress tests during the build stage, the reporting is not there. You only see whether the tests have passed or failed, even though the documentation states, "Amplify Hosting offers a deeper integration with Cypress that allows you to generate a UI report for your tests." The configurations for report generation are still present, as mentioned in the same AWS blog post: https://aws.amazon.com/blogs/mobile/running-end-to-end-cypress-tests-for-your-fullstack-ci-cd-deployment-with-amplify-console/.  
This lack of detailed is not helpful. The documentation should be updated to reflect these changes, or the previous level of Cypress support should be reinstated.

**Comment by Jay2113** [comment]
Hi @hackmajoris 👋 , thanks for reaching out. We have identified this as a bug and are actively working on a fix for it. I'll keep the thread posted with any updates.

**Comment by Jay2113** [comment]
Hi @hackmajoris, thanks for your patience. We have released a fix for this feature and you should now be able to download the test artifacts and the Cypress results from the new Amplify console experience.

<img width="966" alt="Screenshot 2024-06-14 at 9 49 09 AM" src="https://github.com/aws-amplify/amplify-backend/assets/38470430/8d0962ac-140a-4a12-aa66-8c0f1fb69877">

**Comment by hackmajoris** [comment]
> Hi @hackmajoris, thanks for your patience. We have released a fix for this feature and you should now be able to download the test artifacts and the Cypress results from the new Amplify console experience.
> 


Hey @Jay2113, while testing your fix, I can see that you can download those artifacts only  for the successful builds. For the failing one I  have just this option: 

<img width="362" alt="image" src="https://github.com/aws-amplify/amplify-backend/assets/3758212/d89ec7ca-11d9-4326-adfd-320b8bb738c4">

This is not very helpful, since usually you need to see those artifacts when the build fails.

The build may fail for different reasons and it can fail before executing the Cypress tests. In that case, the download of artificers can be omitted. But, if the build fails because of Cypress failed tests, the option to download the Cypress results should be in place.

**Comment by Tony-Donghua-Han** [comment]
Having the same issue, is there is workout for us to fetch the artifacts right now?

**Comment by hackmajoris** [comment]
> Having the same issue, is there is workout for us to fetch the artifacts before we get another fix?

You can use this command: aws amplify get-job --region eu-central-1 --app-id APP_ID --branch-name BRANCH_NAME --job-id JOB_NUMBER  --profile  AWS_PROFILE

**Comment by Jay2113** [comment]
@hackmajoris @Tony-Donghua-Han thank you for verifying the fix and providing feedback on allowing test artifact downloads upon failure. We are investigating into how we can support this functionality to improve the experience.

**Comment by Jay2113** [comment]
@hackmajoris @Tony-Donghua-Han we have prioritized and are actively working on a fix to enable downloading artifacts upon test failures. I'll update the thread when the fix is released. Thanks for your continued patience.

**Comment by Jay2113** [comment]
@hackmajoris @Tony-Donghua-Han 👋 , we have deployed another fix and you should now be able to download the test artifacts even when the tests fail. Can you please verify and confirm the same? Thanks!

**Comment by richardwadsworth** [comment]
@Jay2113 Do I need to do anything to make use of both of these fixes?

On successful builds I still do not have access to the test artifacts

And on failed build I only see the option to download the logs.

App id dsj8xdikh9gco

**Comment by Jay2113** [comment]
Hi @richardwadsworth, I see that your app `dsj8xdikh9gco` has a couple of branches `develop` and `feature/e2e`. The tests are configured for the `feature/e2e` branch, are you unable to download the test artifacts for it? Can you share a screenshot?

**Comment by richardwadsworth** [comment]
> Hi @richardwadsworth, I see that your app `dsj8xdikh9gco` has a couple of branches `develop` and `feature/e2e`. The tests are configured for the `feature/e2e` branch, are you unable to download the test artifacts for it? Can you share a screenshot?

Hi @Jay2113 , the tests are being run in the feature/e2e branch.  I can download the test artefacts zip using "aws amplify get-job" but the options to download the test artefacts via the UI (on a successful or failed build) are not available on the UI.  Refer to the screen shot.

<img width="1415" alt="Screenshot 2024-06-27 at 09 56 55" src="https://github.com/aws-amplify/amplify-backend/assets/1564017/76e0c794-d0cb-42a3-b5f2-877edf443661">

**Comment by Jay2113** [comment]
Hi @richardwadsworth, thanks for your continued cooperation. To expedite the troubleshooting process, we would like to setup a call with you. Can you share your availability via a DM on our [community discord server](https://discord.gg/amplify). My username is Jay Raval.

**Comment by hackmajoris** [comment]
@Jay2113  I can now download the artifacts for the failed builds. @richardwadsworth Try to re-run the build again. The download of artifacts it's not possible for the historical builds.

**Comment by hackmajoris** [comment]
Thank for this fix. Good job!
