### ISSUE TITLE
Can't select Amazon Linux 2023 (Default) as the build image

### ISSUE THREAD

**Issue by renchris** [aws-amplify/amplify-backend#1660]
### Environment information

```plain text
-
```

### Description

The default pre-selected build setting image was `Amazon Linux 2023 (default)` for my NextJS App Router Amplify App. After changing the build image between `Amazon Linux 1`, `Amazon Linux 2`, and/or `Custom Build Image`, the interface does not allow you to change back to `Amazon Linux 2023 (default)`.

I require `Amazon Linux 2023 (default)` as the build image for my application to run so I am currently blocked without a way to successfully build my app

**Comment by Jay2113** [comment]
@renchris 👋 , thanks for reaching out. I was able to reproduce this behavior and marking this as a bug. 

In the meantime, as a workaround you can manually update the `_CUSTOM_IMAGE` environment variable for your app `amplify:al2023`  to use the Amazon Linux 2023 default image.

**Comment by Jay2113** [comment]
@renchris we have deployed a fix for this issue. Can you please confirm if you are now able to switch back to the `Amazon Linux 2023` image in the console? Thanks!

**Comment by renchris** [comment]
I can now select and switch back to the `Amazon Linux 2023 (default)` build image. Thanks!

**Comment by emmareynne** [comment]
This still happened to me in a project in my apps that were on Linux 2 before the release of Linux 2023. The environment variable allowed me to switch, though.
