### ISSUE TITLE
Deployment fails when I add "npx ampx pipeline-deploy" to the build settings

### ISSUE THREAD

**Issue by nikolai-kosolapov** [aws-amplify/amplify-backend#1674]
### Environment information

```plain text
System:
  OS: Windows 11 10.0.22631
  CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Memory: 17.61 GB / 31.88 GB
Binaries:
  Node: 20.14.0 - C:\Program Files\nodejs\node.EXE
  Yarn: undefined - undefined
  npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 1.0.3
  @aws-amplify/backend-cli: 1.0.4
  aws-amplify: 6.3.7
  aws-cdk: 2.147.0
  aws-cdk-lib: 2.147.0
  typescript: 5.5.2
AWS environment variables:
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_STS_REGIONAL_ENDPOINTS = regional
No CDK environment variables
  Node: 20.14.0 - C:\Program Files\nodejs\node.EXE
  Yarn: undefined - undefined
  npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 1.0.3
  @aws-amplify/backend-cli: 1.0.4
  aws-amplify: 6.3.7
  aws-cdk: 2.147.0
  aws-cdk-lib: 2.147.0
  typescript: 5.5.2
AWS environment variables:
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_STS_REGIONAL_ENDPOINTS = regional
No CDK environment variables
`
```

### Description

I'm trying to add Amplify to my existing Expo React Native app.

I was trying to add Authentication but nothing happened. Then I noticed that in build section there is no backend section.
A added the following:

```
backend:
  phases:
    build:
      commands:
        - npm ci --cache .npm --prefer-offline
        - npx ampx pipeline-deploy --branch $AWS_BRANCH --app-id $AWS_APP_ID
```
but now I have errors during the deployment:
```
2024-06-24T07:51:09.370Z [INFO]: # Executing command: npx ampx pipeline-deploy --branch $AWS_BRANCH --app-id $AWS_APP_ID
2024-06-24T07:51:18.075Z [INFO]: 
2024-06-24T07:51:24.280Z [INFO]: ✨  Synthesis time: 0.06s
2024-06-24T07:51:24.380Z [INFO]: [33mcurrent credentials could not be used to assume 'arn:aws:iam::073653171576:role/cdk-hnb659fds-deploy-role-073653171576-us-east-1', but are for the right account. Proceeding anyway.[39m
2024-06-24T07:51:24.382Z [INFO]: [33mcurrent credentials could not be used to assume 'arn:aws:iam::073653171576:role/cdk-hnb659fds-deploy-role-073653171576-us-east-1', but are for the right account. Proceeding anyway.[39m
2024-06-24T07:51:24.384Z [INFO]: [33mcurrent credentials could not be used to assume 'arn:aws:iam::073653171576:role/cdk-hnb659fds-deploy-role-073653171576-us-east-1', but are for the right account. Proceeding anyway.[39m
2024-06-24T07:51:24.385Z [INFO]: [33mcurrent credentials could not be used to assume 'arn:aws:iam::073653171576:role/cdk-hnb659fds-deploy-role-073653171576-us-east-1', but are for the right account. Proceeding anyway.[39m
2024-06-24T07:51:24.386Z [INFO]: [33mcurrent credentials could not be used to assume 'arn:aws:iam::073653171576:role/cdk-hnb659fds-deploy-role-073653171576-us-east-1', but are for the right account. Proceeding anyway.[39m
2024-06-24T07:51:24.388Z [INFO]: [33mcurrent credentials could not be used to assume 'arn:aws:iam::073653171576:role/cdk-hnb659fds-deploy-role-073653171576-us-east-1', but are for the right account. Proceeding anyway.[39m
2024-06-24T07:51:24.389Z [INFO]: [33mcurrent credentials could not be used to assume 'arn:aws:iam::073653171576:role/cdk-hnb659fds-deploy-role-073653171576-us-east-1', but are for the right account. Proceeding anyway.[39m
2024-06-24T07:51:24.390Z [INFO]: [33mcurrent credentials could not be used to assume 'arn:aws:iam::073653171576:role/cdk-hnb659fds-deploy-role-073653171576-us-east-1', but are for the right account. Proceeding anyway.[39m
2024-06-24T07:51:24.792Z [INFO]: 
2024-06-24T07:51:24.834Z [INFO]: 
2024-06-24T07:51:24.835Z [WARNING]: ampx pipeline-deploy
                                    Command to deploy backends in a custom CI/CD pipeline. This command is not inten
                                    ded to be used locally.
                                    Options:
                                    --debug            Print debug logs to the console  [boolean] [default: false]
                                    --help             Show help                                         [boolean]
                                    --branch           Name of the git branch being deployed   [string] [required]
                                    --app-id           The app id of the target Amplify app    [string] [required]
                                    --outputs-out-dir  A path to directory where amplify_outputs is written. If no
                                    t provided defaults to current process working directory.
                                    [string]
                                    --outputs-version  Version of the configuration. Version 0 represents classic
                                    amplify-cli config file amplify-configuration and 1 represe
                                    nts newer config file amplify_outputs
                                    [string] [choices: "0", "1"] [default: "1"]
2024-06-24T07:51:24.835Z [INFO]: CloudFormationDeploymentError: The CloudFormation deployment has failed.
                                 Resolution: Find more information in the CloudFormation AWS Console for this stack.
2024-06-24T07:51:24.835Z [INFO]: Cause: ❌ Deployment failed: Error: amplify-d36cs3s365wjpi-dev-branch-778c52acd7: This CDK deployment requires bootstrap stack version '6', but during the confirmation via SSM parameter /cdk-bootstrap/hnb659fds/version the following error occurred: AccessDeniedException: User: arn:aws:sts::073653171576:assumed-role/AemiliaControlPlaneLambda-CodeBuildRole-1PJH7JZRIQRPI/AWSCodeBuild-18dc5e99-c364-455f-a6c2-c76ece8bae03 is not authorized to perform: ssm:GetParameter on resource: arn:aws:ssm:us-east-1:073653171576:parameter/cdk-bootstrap/hnb659fds/version because no identity-based policy allows the ssm:GetParameter action[39m
2024-06-24T07:51:24.839Z [INFO]: CloudFormationDeploymentError: The CloudFormation deployment has failed.
2024-06-24T07:51:24.839Z [INFO]: Resolution: Find more information in the CloudFormation AWS Console for this stack.
                                 Cause: ❌ Deployment failed: Error: amplify-d36cs3s365wjpi-dev-branch-778c52acd7: This CDK deployment requires bootstrap stack version '6', but during the confirmation via SSM parameter /cdk-bootstrap/hnb659fds/version the following error occurred: AccessDeniedException: User: arn:aws:sts::073653171576:assumed-role/AemiliaControlPlaneLambda-CodeBuildRole-1PJH7JZRIQRPI/AWSCodeBuild-18dc5e99-c364-455f-a6c2-c76ece8bae03 is not authorized to perform: ssm:GetParameter on resource: arn:aws:ssm:us-east-1:073653171576:parameter/cdk-bootstrap/hnb659fds/version because no identity-based policy allows the ssm:GetParameter action[39m
2024-06-24T07:51:24.939Z [ERROR]: !!! Build failed

```

**Comment by ykethan** [comment]
Hey @anbraten @nikolai-kosolapov, does the service role attached to the app have the [AmplifyBackendDeployFullAccess](https://us-east-1.console.aws.amazon.com/iam/home?region=us-east-1#/policies/details/arn%3Aaws%3Aiam%3A%3Aaws%3Apolicy%2Fservice-role%2FAmplifyBackendDeployFullAccess) attached?

**Comment by nikolai-kosolapov** [comment]
I have to create a new app. In old one I cannot set the role even if ui says it is set up successfully.

**Comment by Jay2113** [comment]
@nikolai-kosolapov @anbraten Can you confirm if these are the accurate reproduction steps for the issue you're facing. If not, feel free to provide any additional details or clarifications to ensure we have a clear understanding of the problem:

1. Start with an existing Gen 1 frontend-only app and add a Gen 2 backend to it.
2. Update the amplify.yml file to include the relevant backend build steps `ampx pipeline-deploy`.
3. Deployment fails due to missing service role.
4. Create an IAM role with [AmplifyBackendDeployFullAccess](https://docs.amplify.aws/react/reference/iam-policy/#branch-deployments) policy.
5. Navigate to `General settings` -> `Edit` -> Select the service role -> `Save`.
6. The service role is not persisted in the console after saving.

**Comment by nikolai-kosolapov** [comment]
I had my react native repo without amplify app.
I created an Amplify app from that repo.
Then I added Amplify code locally (authentication)
I added backend section to the build configuration.

**Comment by Jay2113** [comment]
@nikolai-kosolapov Thanks for providing the steps to reproduce the issue. The deployment error is caused by a missing IAM service role. Branch deployments require the [AmplifyBackendDeployFullAccess](https://docs.aws.amazon.com/amplify/latest/userguide/security-iam-awsmanpol.html#security-iam-awsmanpol-AmplifyBackendDeployFullAccess) managed policy to deploy backend resources during a full-stack deployment. Since you added a Gen 2 backend to an existing app, you need to manually add the role for the app. 

Additionally, we're working on a fix to persist the role in the console after saving it. As a workaround, you can use the AWS CLI to add the role to your app:
```
aws amplify update-app --region ${REGION} --app-id ${APP_ID} --iam-service-role-arn ${SERVICE_ROLE_ARN}
```

**Comment by Jay2113** [comment]
> I have to create a new app. In old one I cannot set the role even if ui says it is set up successfully.
> 
> <img alt="image" width="907" src="https://private-user-images.githubusercontent.com/16111596/342578377-a73aec7c-c38c-4b25-b453-ea905333b897.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NTk4ODAsIm5iZiI6MTcyMTY1OTU4MCwicGF0aCI6Ii8xNjExMTU5Ni8zNDI1NzgzNzctYTczYWVjN2MtYzM4Yy00YjI1LWI0NTMtZWE5MDUzMzNiODk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDE0NDYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZmFkMTg2ZTFkOTJhNzYwNzM5ZGM3OTZiZjBlMTUwYzlhNzFmODRhMmVhZDNlYzVjZTFjNWZmMjIyYmFmY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JKpQsqW2dWSKKZKPx8YZx3lvKVg6H_XlMEPtC5vE6iw">

@nikolai-kosolapov We have deployed a fix for this issue and the service role should now persist correctly in the Amplify console after saving it from `App settings > General settings > Edit`.

**Comment by catproof** [comment]
@Jay2113 the issue still persists. If you have an existing amplify app and add the backend to it later, you get this error
