### ISSUE TITLE
Build stuck on extracting cache for next.js site

### ISSUE THREAD

**Issue by mcfry** [aws-amplify/amplify-backend#1765]
### Environment information

```plain text
n/a
```

### Description

Previously, all of my builds would succeed, but they've randomly started to fail and now I have to remove the following lines from my amplify.yml file:

  cache:
    paths:
      - .next/cache/**/*
      - node_modules/**/*
      
In order for the build to deploy, otherwise it gets stuck on:

2024-07-19T15:46:29.824Z [INFO]: # Extracting cache...

For context, this is a Next.js 14.2.5 site. 

Thanks.

**Comment by Jay2113** [comment]
Hi @mcfry 👋 , thanks for reaching out. Are you using `pnpm` as the package manager at build time? For projects using `pnpm` specifically, you can utilize the following cache path:
```
cache:
  paths:
    - $(pnpm store path)
```

The `pnpm` store acts as a central cache for all dependencies, as documented here: https://pnpm.io/cli/store#path. 

Additionally, did you observe an out of memory error/banner in the console?

**Comment by hwildwood** [comment]
I'm getting the same issue.  I'm using PNPM but it's getting stuck here:

```
2024-07-23T09:54:31.485Z [INFO]: # Retrieving cache...
2024-07-23T09:55:15.260Z [INFO]: # Extracting cache...
```

No changes on our side.

**Comment by TomBell95** [comment]
I'm also getting this issue - nothing has changed our side to cause this. Added `$(pnpm store path)` as per @Jay2113's comment but still not resolved.

Any help?

**Comment by tomfloresa** [comment]
Same problem here. Takes forever.

**Comment by Jay2113** [comment]
@mcfry @hwildwood @TomBell95 @tomfloresa can you share your Amplify app ids?

**Comment by Jay2113** [comment]
As we continue investigating this issue, in the interim can you remove the cache path from the build specification or `amplify.yml` file, and then redeploy your application. Please let us know if this resolves the problem or if you are still experiencing any issues.

**Comment by TomBell95** [comment]
Thanks @Jay2113 - my app ID's:
- d1jr2mxwfz2c9v
- d17dve74yk7ax7
- d1qqp0zr1l3zrm

Removed the cache path and still having the same issue, hangs on `Extracting cache...` then times out after 30 mins

**Comment by hwildwood** [comment]
I tried removing the cache path as well and it didn't help.  I ended up having to delete the amplify app and re-deploy it using terraform.

**Comment by Jay2113** [comment]
@hwildwood @tomfloresa @mcfry can you confirm if your app uses the `pnpm` package manager at build time? This will be helpful for us to narrow down the root cause.

**Comment by hwildwood** [comment]
> @hwildwood @tomfloresa @mcfry can you confirm if your app uses the `pnpm` package manager at build time? This will be helpful for us to narrow down the root cause.

Yes, I use PNM.  This is my build specification.

```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - corepack enable && corepack enable pnpm
        - pnpm install
    build:
      commands:
        - pnpm build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      - .next/cache/**/*
```

**Comment by TomBell95** [comment]
@Jay2113 my buildspec
```yaml
version: 1
frontend:
    phases:
        preBuild:
            commands:
                    - npm install -g pnpm@v8.12.0
                    - pnpm install --frozen-lockfile
        build:
            commands:
                    - pnpm run build
     artifacts:
         baseDirectory: .next
         files:
            - '**/*'
     cache:
          paths:
              - node_modules/**/*
```

**Comment by Jay2113** [comment]
@mcfry @hwildwood @TomBell95 @tomfloresa We have identified the root cause of the issue. Please find the details below:

Amplify experienced a problem extracting cache artifacts for `pnpm` builds in the regions `ca-central-1`, `eu-south-1`, `us-east-2`, `us-east-1`, `eu-west-1`, and `ap-southeast-1`. The issue has been resolved and the service is operating normally. You can retry any failed deploys from the Amplify Console.

Can you please retry and confirm if you are now unblocked?

**Comment by Jay2113** [comment]
I am closing this thread since the issue has been resolved.

**Comment by mcfry** [comment]
Yes, I was using pnpm. If I run into any further issues I'll post them. Thanks!

**Comment by ailen0ada** [comment]
I still have the same problem on `ap-northeast-1` . buildspec is as follows, and yes, I am using pnpm.

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - corepack enable
        - pnpm install --frozen-lockfile
        - pnpm exec ampx pipeline-deploy --branch $AWS_BRANCH --app-id $AWS_APP_ID
frontend:
  phases:
    build:
      commands:
        - pnpm run build
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

**Comment by koukimetal** [comment]
I get the issue on `ap-southeast-2`
error happens here 
```
/node_modules/aws-cdk-lib] EEXIST: file already exists, rename
```
removing cache paths makes the build pass but I prefer using cache
