### ISSUE TITLE
SAML as externalProviders failed to deploy

### ISSUE THREAD

**Issue by funjay** [aws-amplify/amplify-backend#766]
### Environment information

```plain text
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 7.85 GB / 31.74 GB
  Binaries:
    Node: 20.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.7.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
    bun: Not Found
    Watchman: Not Found
  npmPackages:
    @aws-amplify/backend: ^0.5.5 => 0.5.5
    @aws-amplify/backend-cli: ^0.9.1 => 0.9.1
    aws-amplify: ^6.0.5 => 6.0.5
    aws-cdk: Not Found
    aws-cdk-lib: Not Found
    typescript: ^5.3.2 => 5.3.2
```

### Description

My auth config

    externalProviders: {

      saml: {
        metadata: {
          metadataContent: mcontent, //content from metadatafile
          metadataType: UserPoolIdentityProviderSamlMetadataType.FILE
        },
        name: 'testme',
             
      }

Error trying to deploy sandbox

Failed resources:
amplify-xxxxxx-sandbox-add8e06832-auth179371D7-O6RLFUCCZ2RB | 20:26:26 | CREATE_FAILED        | AWS::Cognito::IdentityPool | auth/amplifyAuth/IdentityPool (amplifyAuthIdentityPool3FDE84CC) Identity provider arn:us-east-1:iam::xxxxxxx:saml-provider/mytest is not valid for account xxxxxxxxxx (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 117101ad-1626-4a86-9465-1ee790022864; Proxy: null)

Thanks

I think this is a bug as userpool saml provider do not use iam saml provider, i dont know where the iam is coming from. 

thanks

**Comment by josefaidt** [comment]
Hey @funjay :wave: thanks for raising this! I was able to reproduce this, and it is caused by the ARN that is constructed for the SAML provider. The ARN issue is being tracked here https://github.com/aws-amplify/amplify-backend/issues/796, but I will leave this open to confirm SAML is working as expected afterwards

**Comment by funjay** [comment]
Thanks @josefaidt 
any workaround at the moment?

**Comment by josefaidt** [comment]
Hey @funjay apologies for the delay but this is now resolved 🙂 please upgrade to the latest backend package and redeploy

**Comment by imiosga** [comment]
@josefaidt For me it is not caused by the ARN formatting and even with the fix for #796 I still get the same deployment errors. It's caused by something else:

This ```externalProviders: {

  saml: {
    metadata: {
      metadataContent: mcontent, //content from metadatafile
      metadataType: UserPoolIdentityProviderSamlMetadataType.FILE
    },
    name: 'testme',
         
  }``` creates a federated identity provider _within the Cognito user pool_ but then tries to reference a (non-existant) identity provider _within the identity pool_ by ARN. Take a look at https://github.com/imiosga/amplify-backend/blob/2a75b08dcd19ddebba392742868ddb73b87c929c/packages/auth-construct/src/construct.ts#L342 - once the ARN is not created and added to the identity pool, deployment runs through.

**Comment by exai-sukh** [comment]
I am also encountering this issue.

**Comment by exai-sukh** [comment]
Thanks everyone for your time and attention to this bug. I'm currently in the process of migrating from Amplify V1 to V2, and unfortunately, this is causing a roadblock. If there are any specific details or logs that could aid in troubleshooting or if assistance is needed for testing, please don't hesitate to reach out.

**Comment by imiosga** [comment]
@exai-sukh I fixed it in a local fork by commenting out the place where the provider ARN - that is pointing to nowhere - is created. In `packages/auth-construct/src/construct.ts:setupIdentityPool` I did:
`  // if (providerSetupResult.saml) {
    //   identityPool.samlProviderArns = [
    //     arnBuilder({
    //       service: 'iam',
    //       region,
    //       accountId: Stack.of(this).account,
    //       resource: `saml-provider/${providerSetupResult.saml.providerName}`,
    //     }),
    //   ];
    // }`
